language: python
dist: xenial
install:
- pip install -r requirements-test.txt -r requirements.txt
jobs:
  include:
  - stage: test
    name: Code format check
    script:
    - black --check .
  - stage: test
    name: Lint
    script:
    - echo linting
  - stage: test
    name: Run Tests
    python: 3.7
    script:
    - nose2 -v
    after_script:
    - codecov
  - stage: deploy
    script: "/bin/true"
    deploy:
      provider: pypi
      user: "__token__"
      skip_upload_docs: true
      skip_existing: true
      password:
        secure: SBsXJFidd2HxgBNz8zwhHiqc4mtZoBQs7RaHdWIVa0k2rp4ApGm+ebmtvsAAFHVFW8XzddWxpejx9qRdcSH87yBc/eTaudSzj8igr05Ccpy+60M7kQRysskZm7Tn1HvyLLSyzVCwdpYso7+VeX8vCvuHqB+xIChNpduqAiVDHIhALN5/DIGEM9KehglHl2BekFjpUh3fYJ17gvtHl5VFPenKjFM01KrxCvSOJqXG5P4DrFFhfuBtxOFzxWS0DVVivwacNaYKCjWzJEH8bHbr0CSCawMMD4NZ4r+P0qo7FQguH3VnmuXuu1cao1ACgXWpCerdrXP1oo4V8QCcAf4Nh6q6Elvu1sKh/o65BBZ/JehVl3FSFEhbMDcPGfZ1f5ajLasH0aPHHJFaDTSOLyMUc0ksNse8OFrLu3/sfvFMbbOr27Dp1woEjG2SaS5Iv7+sVDpKqn2oPUqxwjvzt1HIrM3vLvWcrrXTCrHWpoOVQRyg4br3Kp32t8nfXSY+wWbbCXHX9gkQhs6UKJM3Jcf/FBnCnzH0DNlPkDcFM9Gl2etsl3w29D04Fp5sYTXjjwJ/6efJLxkEhaavuf+1qEpy/cvDrWuzLAec4LKm8BwmsQtH3RczrpIzq3s6rj17SLrrt8D+vtrYi7zlXSShOyo7ErAN81CUOWsPGVIvgpc25pM=
      on:
        tags: true
  
